# Generated by Django 3.0.2 on 2020-06-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0012_auto_20200228_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageprograms',
            name='collateral_object_comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий к залоговый объект'),
        ),
        migrations.AddField(
            model_name='mortgageprograms',
            name='collateral_object_is_active',
            field=models.BooleanField(default=False, verbose_name='Залоговый объект'),
        ),
    ]
