# Generated by Django 3.0.2 on 2020-06-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0013_auto_20200604_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageprograms',
            name='overstatement_comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий к завышению'),
        ),
        migrations.AddField(
            model_name='mortgageprograms',
            name='overstatement_is_active',
            field=models.BooleanField(default=False, verbose_name='Завышение, Есть/нет'),
        ),
        migrations.AddField(
            model_name='mortgageprograms',
            name='spouse_exclusion_comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий к исключению супруги(а)'),
        ),
        migrations.AddField(
            model_name='mortgageprograms',
            name='spouse_exclusion_is_active',
            field=models.BooleanField(default=False, verbose_name='Исключение супруги(а) согласием'),
        ),
        migrations.AddField(
            model_name='mortgageprograms',
            name='wetpoint_transfer',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], db_index=True, max_length=255, verbose_name='Перенос мокрой точки'),
        ),
        migrations.AddField(
            model_name='mortgageprograms',
            name='wetpoint_transfer_comment',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Комментарий к мокрой точки'),
        ),
    ]
