# Generated by Django 3.0.2 on 2020-06-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0014_auto_20200611_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='banks',
            name='link_docs',
            field=models.TextField(blank=True, verbose_name='Ссылка на документы'),
        ),
        migrations.AlterField(
            model_name='mortgageprograms',
            name='add_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
