# Generated by Django 3.0.2 on 2020-07-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0015_auto_20200613_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageprograms',
            name='is_use_preference_bank',
            field=models.BooleanField(default=True, verbose_name='Применять преференцию банка к программе'),
        ),
    ]
